# Site settings
title: Navin Verma
email: navinkumarverma@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    My experiences with Math, Philosofy and Code.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: navinkumarverma
github_username:  navinkverma

# Build settings
markdown: kramdown
